import {alpha,alpha_dash,alpha_num,alpha_spaces,between, confirmed, digits, dimensions,
email,
ext,
image,
integer,
is,
is_not,
length,
max,
max_value,
mimes,
min,
min_value,
not_one_of,
numeric,
one_of,
regex,
required,
size,
toTypedSchema,
url} from '@vee-validate/rules';

const AllRules = {
    alpha : alpha,
    alpha_dash : alpha_dash,
    alpha_num : alpha_num,
    alpha_spaces : alpha_spaces,
    between : between,
    confirmed : confirmed,
    digits : digits,
    dimensions : dimensions,
    email : email,
    ext : ext,
    image : image,
    integer : integer,
    is : is,
    is_not : is_not,
    length : length,
    max : max,
    max_value : max_value,
    mimes : mimes,
    min : min,
    min_value : min_value,
    not_one_of : not_one_of,
    numeric : numeric,
    one_of : one_of,
    regex : regex,
    required : required,
    size : size,
    toTypedSchema : toTypedSchema,
    url : url
}

export default AllRules;
